// <auto-generated />
using KaliteKontrol.ModelsDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KaliteKontrol.Migrations
{
    [DbContext(typeof(KaliteContext))]
    [Migration("20251004202019_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KaliteKontrol.ModelsDb.ADIM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ADIM_NO")
                        .HasColumnType("int");

                    b.Property<string>("BC_TANIM")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ETIKET")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("HAT_ADI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ISLEM_ADI")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ISLEM_NO")
                        .HasColumnType("int");

                    b.Property<string>("IST_ADI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IST_NO")
                        .HasColumnType("int");

                    b.Property<int>("PROG_NO")
                        .HasColumnType("int");

                    b.Property<string>("RESIM_YOLU")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("REWORK_PROG_NO")
                        .HasColumnType("int");

                    b.Property<int>("REWORK_SIKICI_NO")
                        .HasColumnType("int");

                    b.Property<int>("SIKICI_NO")
                        .HasColumnType("int");

                    b.Property<int>("SIKIM_ADEDI")
                        .HasColumnType("int");

                    b.Property<int>("SURE")
                        .HasColumnType("int");

                    b.Property<string>("TIP_KODU")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("ID");

                    b.ToTable("ADIM");
                });

            modelBuilder.Entity("KaliteKontrol.ModelsDb.ISLEMLER", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ISLEM_ADI")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ISLEM_NO")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ISLEM_NO")
                        .IsUnique();

                    b.ToTable("ISLEMLER");
                });

            modelBuilder.Entity("KaliteKontrol.ModelsDb.Kullanicilar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int?>("YetkiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.HasIndex("YetkiId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("KaliteKontrol.ModelsDb.Yetki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("YetkiAdi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Yetki");
                });

            modelBuilder.Entity("KaliteKontrol.ModelsDb.Kullanicilar", b =>
                {
                    b.HasOne("KaliteKontrol.ModelsDb.Yetki", "Yetki")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("YetkiId");

                    b.Navigation("Yetki");
                });

            modelBuilder.Entity("KaliteKontrol.ModelsDb.Yetki", b =>
                {
                    b.Navigation("Kullanicilar");
                });
#pragma warning restore 612, 618
        }
    }
}
